name: johncaswell
favicon: null
layout_spectrum: 0.8011363556142896
typography_spectrum: 0.23965460411272943
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.1760911145247519
  lightness: 0.7637987514026463
  saturation: 0.6179501246660948
  rhythmicContrast: 0.7546061782632023
purpose: []
