name: johncaswell
favicon: null
layout_spectrum: 0.2607
typography_spectrum: 0.23965460411272943
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0204c'
    - '#ff681f'
    - '#ffffff'
    - '#ff9918'
    - '#d68ca2'
  brandStrength: 0.1875
  lightness: 0.7637987514026463
  saturation: 0.6179501246660948
  rhythmicContrast: 0.7546061782632023
purpose: []
