name: johncaswell
favicon: null
layout_spectrum: 0.26037
typography_spectrum: 0.5556492
title: Just Thinking
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2ce2e'
    - '#be244e'
    - '#4e7d44'
    - '#064577'
    - '#ffffff'
  brandStrength: 0.6875
  lightness: 0.801855
  saturation: 0.6644182
  rhythmicContrast: 0.8381113
purpose: []
